# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:13:37+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class ClickModel(BaseModel):
    alias: Optional[str] = None
    aliasId: Optional[str] = None
    browser: Optional[str] = None
    country: Optional[str] = None
    createdAt: Optional[int] = None
    destination: Optional[str] = None
    domain: Optional[str] = None
    os: Optional[str] = None
    referrer: Optional[str] = None
    userAgent: Optional[str] = None


class ClickModelPg(BaseModel):
    accountId: Optional[str] = None
    alias: Optional[str] = None
    aliasId: Optional[str] = None
    browser: Optional[str] = None
    country: Optional[str] = None
    createdAt: Optional[int] = None
    destination: Optional[str] = None
    domain: Optional[str] = None
    id: Optional[int] = None
    os: Optional[str] = None
    referrer: Optional[str] = None
    userAgent: Optional[str] = None


class ClicksFilterModel(BaseModel):
    aliasId: Optional[str] = Field(None, description='Alias Id', examples=['aBcDe012'])
    dateFrom: Optional[str] = Field(
        None, description='date From', examples=['2001-05-02']
    )
    dateTo: Optional[str] = Field(None, description='date To', examples=['2001-05-02'])
    domain: Optional[str] = Field(
        None, description='Domain name', examples=['short.fyi']
    )
    lastId: Optional[int] = Field(None, description='last Id', examples=[100])


class CreateAliasResponseModel(BaseModel):
    aliasName: Optional[str] = Field(None, examples=['aBcDe012'])
    domainName: Optional[str] = Field(None, examples=['your.domain.com'])
    shortUrl: Optional[str] = Field(None, examples=['https://your.domain.com/aBcDe012'])


class DestinationModel(BaseModel):
    country: Optional[str] = Field(
        None,
        description='ISO alpha-2 [country code](//en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements)',
    )
    os: Optional[str] = Field(
        None, description='Please check the [supported OS list](#tag/OperatingSystems)'
    )
    url: str


class GetAliasModel(BaseModel):
    createdAt: Optional[int] = None
    domainName: Optional[str] = Field(None, examples=['your.domain.com'])
    name: Optional[str] = None
    updatedAt: Optional[int] = None


class GetAliasesModel(BaseModel):
    aliases: Optional[List[str]] = None
    lastId: Optional[str] = None


class GetClicksModel(BaseModel):
    clicks: Optional[List[ClickModel]] = None
    lastId: Optional[str] = None


class MetaTagModel(BaseModel):
    content: str
    name: str


class SnippetModel(BaseModel):
    id: str = Field(
        ..., description='Please check the [supported snippets list](#tag/Snippets)'
    )
    parameters: Optional[Dict[str, str]] = None


class AliasModel(BaseModel):
    createdAt: Optional[int] = Field(None, examples=[1595845801514])
    destinations: Optional[List[DestinationModel]] = None
    domainName: Optional[str] = Field(None, examples=['your.domain.com'])
    metatags: Optional[List[MetaTagModel]] = None
    name: str = Field(..., examples=['aBcDe012'])
    snippets: Optional[List[SnippetModel]] = None
    updatedAt: Optional[int] = Field(None, examples=[1595845801514])


class CreateAliasModel(BaseModel):
    destinations: Optional[List[DestinationModel]] = None
    metatags: Optional[List[MetaTagModel]] = None
    snippets: Optional[List[SnippetModel]] = None
